    services:
      db:
        image: postgres:15
        environment:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"
      web:
        build: .
        environment:
          # Esta variável ajuda o Python a encontrar o projeto
          - PYTHONPATH=/app
        command: gunicorn novo_projeto_django.wsgi:application --bind 0.0.0.0:8000
        volumes:
          - .:/app
        ports:
          - "8000:8000"
        depends_on:
          - db
    